### ISSUE TITLE
Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by YueYongDev** [kokohuang/flutter_easyloading#85]
**Describe the bug**
when I use this plugin on flutter web, it crashes, the bug description is "Unsupported operation: Platform._operatingSystem
The relevant error-causing widget was: ", it says "flutter_easyloading-2.2.2/lib/src/widgets/loading.dart:62:14", the code as follow
```
@override
  Widget build(BuildContext context) {
    return Material(
      child: Overlay(
        initialEntries: [
          EasyLoadingOverlayEntry(
            builder: (BuildContext context) => widget.child,
          ),
          _overlayEntry,
        ],
      ),
    );
  }
```

**Screenshots**
![](https://user-images.githubusercontent.com/30254847/103968272-7b490e00-519e-11eb-85e8-a6645f317c9b.png)

**Comment by syleishere** [comment]
I am getting following for web when trying to display a toast:

Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (http://localhost:56903/dart_sdk.js:5347:11)
    at Function._operatingSystem (http://localhost:56903/dart_sdk.js:56279:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:56903/dart_sdk.js:56325:27)
    at get _operatingSystem (http://localhost:56903/dart_sdk.js:56238:27)
    at Function.desc.get [as _operatingSystem] (http://localhost:56903/dart_sdk.js:5852:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:56903/dart_sdk.js:56191:26)
    at flashlight_off (http://localhost:56903/packages/musicplayer/fourthpage.dart.lib.js:1763:73)
    at flashlight_off.next (<anonymous>)
    at runBody (http://localhost:56903/dart_sdk.js:39187:34)
    at Object._async [as async] (http://localhost:56903/dart_sdk.js:39218:7)
    at fourthpage.FourthPage.new.flashlight_off (http://localhost:56903/packages/musicplayer/fourthpage.dart.lib.js:1753:20)
    at fourthpage.FourthPage.new.<anonymous> (http://localhost:56903/packages/musicplayer/fourthpage.dart.lib.js:1806:77)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:56903/dart_sdk.js:39187:34)
    at Object._async [as async] (http://localhost:56903/dart_sdk.js:39218:7)
    at http://localhost:56903/packages/musicplayer/fourthpage.dart.lib.js:1805:427
    at ink_well._InkResponseState.new.[_handleTap] (http://localhost:56903/packages/flutter/src/material/icon_button.dart.lib.js:50329:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:56903/packages/flutter/src/gestures/recognizer.dart.lib.js:203:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:56903/packages/flutter/src/gestures/tap.dart.lib.js:417:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:56903/packages/flutter/src/gestures/tap.dart.lib.js:223:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:56903/packages/flutter/src/gestures/tap.dart.lib.js:199:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:56903/packages/flutter/src/gestures/arena.dart.lib.js:222:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:56903/packages/flutter/src/gestures/binding.dart.lib.js:402:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:56903/packages/flutter/src/gestures/binding.dart.lib.js:381:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:56903/packages/flutter/src/rendering/layer.dart.lib.js:6107:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:56903/packages/flutter/src/gestures/binding.dart.lib.js:352:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:56903/packages/flutter/src/gestures/binding.dart.lib.js:325:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:56903/packages/flutter/src/gestures/binding.dart.lib.js:314:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:56903/packages/flutter/src/gestures/binding.dart.lib.js:304:65)
    at Object.invoke1 (http://localhost:56903/dart_sdk.js:185349:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:56903/dart_sdk.js:165680:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:56903/dart_sdk.js:166338:49)
    at http://localhost:56903/dart_sdk.js:166795:28
    at http://localhost:56903/dart_sdk.js:166748:16
    at http://localhost:56903/dart_sdk.js:166442:11

**Comment by ufukhawk** [comment]
same issue

**Comment by syleishere** [comment]
There is a dart native operating system plugin

**Comment by kokohuang** [comment]
> same issue

sorry, I can not reproduce  the problem, it will be helpfull if you can upload a demo project

**Comment by ufukhawk** [comment]
> > same issue
> 
> sorry, I can not reproduce the problem, it will be helpfull if you can upload a demo project

Flutter web also generally gives this error. Can you give a sample working with Flutter web?

**Comment by kokohuang** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/8692455/112286318-28272780-8cc6-11eb-92d1-317e8f04c227.png">

@ufukhawk  example is OK

https://github.com/kokohuang/flutter_easyloading/tree/develop/example

```dart
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.0.1 20B29 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)
```

**Comment by ufukhawk** [comment]
Okay, thank you! worked.

**Comment by syleishere** [comment]
Your plugin is awesome, been using it for quite sometime, always loved it and I am so sad to drop it this week. Flutter is so much simpler with "Get" framework plugin, also rates #3 on plugins worldwide, goodbye bloc thankgod. Their built-in snack bar is good enough for my purposes, but some options on it crash web plugin. I really hope you can include this in their project, I really liked look and feel of this, just no point in me using it now that I have built-in support with GetX.

Awesome job, I really hope you submit a pull request on their project.

**Comment by kokohuang** [comment]
@syleishere thanks
