### ISSUE TITLE
在弹窗显示的同时切换页面或者返回上一页有报错，请问如何处理

### ISSUE THREAD

**Issue by shyx32** [kokohuang/flutter_easyloading#93]
**Describe the Feature request**
Please tell us the problem you are running into that led to you wanting
     a new feature.
![image](https://user-images.githubusercontent.com/16184409/111591384-54dcca00-8802-11eb-91d6-ac26f6bd8ce7.png)

**Comment by kokohuang** [comment]
@shyx32 可否贴一下初始化以及使用的代码看看？

**Comment by yangmingchuan** [comment]
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 789 pos 12: 'elapsedInSeconds >= 0.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:789:12)
#3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1148:15)
#5      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1062:11)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
...

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack: 
#2      SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:532:49)
#3      Ticker.scheduleTick (package:flutter/src/scheduler/ticker.dart:253:47)
#4      Ticker.start (package:flutter/src/scheduler/ticker.dart:162:7)
#5      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:714:42)
#6      AnimationController.repeat (package:flutter/src/animation/animation_controller.dart:638:12)
...
====================================================================================================
